lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600
    user_id_claim: 'email' # Instead of property "user_identity_field: 'email'" otherwise requests will fail with invalid credentials if 'email' is used as identity field instead of 'username'